services:
  layer:
    path: layers/shared

  moc:
    path: services/moc

  digital_signature:
    path: services/digital_signature
    dependsOn:
      - layer
      - firma

  access:
    path: services/access
    dependsOn:
      - layer

  cdts:
    path: services/cdts
    dependsOn:
      - layer

  frontend:
    path: frontend

  firma:
    path: frontend-firma
