service: cdts-digital-signature
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  architecture: arm64
  logRetentionInDays: 14
  environment:
    STAGE: ${self:provider.stage}
    SERVICE: ${self:service}

package:
  individually: true
  patterns:
    - '!**'
    - 'src/**/handler.py'

functions:
  - ${file(./src/sign/function.yml)}
