services:
  migrations:
    path: platform/migrations

  assets:
    path: platform/assets

  auth:
    path: services/auth
    dependsOn:
      - migrations

  banks:
    path: services/banks
    dependsOn:
      - migrations
