"""Deploy-verification tests for signatures/validate_id_front.

Exercises real Rekognition DetectText against a synthetic ID PNG
generated by Pillow with enough printed text (name, ID number,
issue date) that the handler's heuristics pass.

Sad-path variant asserts the empty-ish image bounces with 422.
"""
from __future__ import annotations

import pytest

from tests.integration_helpers import query_one
from tests.integration_signatures import (
    make_synthetic_id_png,
    make_faceless_png,  # doubles as "no text on the image"
    open_ceremony,
    upload_evidence,
    validate_id_side,
    get_ceremony,
)

pytestmark = pytest.mark.integration


def test_validate_id_front_happy_path():
    """After uploading a synthetic ID front PNG, the handler must
    stamp `id_front_validated_at` and return `detected_lines >= 1`.
    DB is the source of truth (see helper's docstring)."""
    ctx = open_ceremony(signer_name="ITest ValidateIDFront")
    try:
        upload_evidence(ctx, "id_front", make_synthetic_id_png("front"), "image/png")
        resp = validate_id_side(ctx, "front")
        assert resp["stage"] in ("created", "identity"), resp
        assert resp["detected_lines"] >= 1, resp
        # State at rest: row has id_front_validated_at set.
        row = query_one(
            "SELECT id_front_validated_at FROM signatures WHERE sign_id = :s",
            s=ctx.sign_id,
        )
        assert row is not None and row["id_front_validated_at"] is not None
    finally:
        ctx.close()


def test_validate_id_front_fails_on_empty_image():
    """An image with no readable text -> 422 id_no_text_detected (or
    a similar 4xx from the OCR pipeline). The row must NOT be marked
    validated."""
    import requests
    from tests.integration_signatures import signatures_api

    ctx = open_ceremony(signer_name="ITest ValidateIDFront Empty")
    try:
        # Solid-color PNG has no text.
        upload_evidence(ctx, "id_front", make_faceless_png(), "image/png")
        resp = requests.post(
            f"{signatures_api()}/signatures/{ctx.sign_id}/evidence/id-front",
            timeout=60,
        )
        assert resp.status_code in (400, 422), resp.text
        # Row is NOT marked validated.
        row = query_one(
            "SELECT id_front_validated_at FROM signatures WHERE sign_id = :s",
            s=ctx.sign_id,
        )
        assert row is not None and row["id_front_validated_at"] is None
    finally:
        ctx.close()


def test_validate_id_front_requires_uploaded_evidence():
    """Calling validate without first uploading the image returns 409
    (no evidence to validate). This proves the handler consults the
    row before calling Rekognition."""
    import requests
    from tests.integration_signatures import signatures_api

    ctx = open_ceremony(signer_name="ITest ValidateIDFront NoEvidence")
    try:
        resp = requests.post(
            f"{signatures_api()}/signatures/{ctx.sign_id}/evidence/id-front",
            timeout=30,
        )
        # 409 (stage not allowed) OR 400 (no evidence). Both are correct
        # signals the handler bailed BEFORE hitting Rekognition.
        assert resp.status_code in (400, 409), resp.text
    finally:
        ctx.close()
